version: '2'

services:
  db:
    container_name: postgres-db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pokemon
    healthcheck:
      test: pg_isready -U user -d ops -h 127.0.0.1
      interval: 5s

  pokemon:
    container_name: pokemon-api
    build: .
    ports:
      - 3000:3000
    healthcheck:
      test: curl -f http://127.0.0.1:4000 || exit 1
    depends_on:
      db:
        condition: service_healthy
